package com.aistudio.jarvis.voiceagent.data.call

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for a concise AI-generated summary of a call handled by Jarvis.
 *
 * Only stored when the user has enabled call summaries (privacy-first default: enabled locally).
 * Full transcripts and audio are NOT stored unless explicitly enabled.
 */
@Entity(tableName = "call_summaries")
data class CallSummaryEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** Display name of the caller, or the number if unknown. */
    val callerName: String,

    /** Raw phone number (stored for display only, not shared). */
    val callerNumber: String,

    /** Epoch milliseconds when the call started. */
    val timestampMs: Long = System.currentTimeMillis(),

    /** How long the Jarvis-handled portion lasted, in seconds. */
    val durationSeconds: Int = 0,

    /** Language detected during the Jarvis conversation (e.g. "English", "Kannada", "Hindi"). */
    val detectedLanguage: String = "Unknown",

    /** Classification from UrgencyClassifier. */
    val urgencyCategory: String = "NORMAL",   // NORMAL | IMPORTANT | POTENTIALLY_URGENT

    /**
     * Short one-to-two sentence reason the caller stated.
     * Minimized to avoid storing sensitive information unnecessarily.
     */
    val callerReason: String = "",

    /** Suggested action for the user (e.g. "Call back when available"). */
    val actionRequired: String = "",

    /** Full one-paragraph human-readable summary generated by Jarvis. */
    val summaryText: String = "",

    /** True when Jarvis accepted and handled this call automatically. */
    val wasAutoAnswered: Boolean = false,

    /** True when the call was declined by user command or setting. */
    val wasDeclined: Boolean = false
)
