package com.aistudio.jarvis.voiceagent.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.aistudio.jarvis.voiceagent.data.call.CallSummaryEntity
import com.aistudio.jarvis.voiceagent.data.call.CallUrgency
import com.aistudio.jarvis.voiceagent.ui.theme.*
import com.aistudio.jarvis.voiceagent.viewmodel.JarvisViewModel
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Screen showing a list of call summaries generated by Jarvis.
 * Allows the user to view details, delete individual entries, or clear all.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CallSummaryScreen(
    viewModel: JarvisViewModel,
    onBack: () -> Unit
) {
    val summaries by viewModel.callSummaries.collectAsStateWithLifecycle()
    var showClearDialog by remember { mutableStateOf(false) }
    var expandedId by remember { mutableStateOf<Long?>(null) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "📋 Call Summaries",
                        color = CyanGlow,
                        fontWeight = FontWeight.Bold,
                        fontSize = 18.sp
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, null, tint = CyanGlow)
                    }
                },
                actions = {
                    if (summaries.isNotEmpty()) {
                        IconButton(onClick = { showClearDialog = true }) {
                            Icon(Icons.Default.DeleteSweep, "Clear all", tint = RoseAccent)
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color(0xFF050B14)
                )
            )
        },
        containerColor = Color(0xFF050B14)
    ) { padding ->

        if (summaries.isEmpty()) {
            EmptyCallSummaryPlaceholder(modifier = Modifier.padding(padding))
        } else {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(padding),
                contentPadding = PaddingValues(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(summaries, key = { it.id }) { summary ->
                    CallSummaryCard(
                        summary = summary,
                        isExpanded = expandedId == summary.id,
                        onToggleExpand = {
                            expandedId = if (expandedId == summary.id) null else summary.id
                        },
                        onDelete = { viewModel.deleteCallSummary(summary.id) }
                    )
                }
                item { Spacer(Modifier.height(24.dp)) }
            }
        }

        // Clear all confirmation dialog
        if (showClearDialog) {
            AlertDialog(
                onDismissRequest = { showClearDialog = false },
                title = { Text("Clear All Summaries", color = TextPrimary) },
                text = {
                    Text(
                        "This will permanently delete all ${summaries.size} call summaries. This cannot be undone.",
                        color = TextSecondary
                    )
                },
                confirmButton = {
                    TextButton(
                        onClick = {
                            viewModel.clearAllCallSummaries()
                            showClearDialog = false
                        }
                    ) {
                        Text("Delete All", color = RoseAccent)
                    }
                },
                dismissButton = {
                    TextButton(onClick = { showClearDialog = false }) {
                        Text("Cancel", color = TextSecondary)
                    }
                },
                containerColor = Color(0xFF0D1117),
                tonalElevation = 0.dp
            )
        }
    }
}

@Composable
private fun CallSummaryCard(
    summary: CallSummaryEntity,
    isExpanded: Boolean,
    onToggleExpand: () -> Unit,
    onDelete: () -> Unit
) {
    val urgencyColor = when (summary.urgencyCategory) {
        "POTENTIALLY_URGENT" -> RoseAccent
        "IMPORTANT" -> AmberAccent
        else -> EmeraldAccent
    }
    val urgencyLabel = when (summary.urgencyCategory) {
        "POTENTIALLY_URGENT" -> "⚠ Potentially Urgent"
        "IMPORTANT" -> "📌 Important"
        else -> "✓ Normal"
    }

    val dateStr = remember(summary.timestampMs) {
        SimpleDateFormat("MMM dd, hh:mm a", Locale.getDefault())
            .format(Date(summary.timestampMs))
    }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(Color(0xFF0D1117))
            .border(1.dp, urgencyColor.copy(alpha = 0.25f), RoundedCornerShape(16.dp))
    ) {
        // Card header — always visible
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            // Caller avatar placeholder
            Box(
                modifier = Modifier
                    .size(44.dp)
                    .clip(RoundedCornerShape(22.dp))
                    .background(urgencyColor.copy(alpha = 0.15f))
                    .border(1.dp, urgencyColor.copy(0.4f), RoundedCornerShape(22.dp)),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    summary.callerName.firstOrNull()?.uppercase() ?: "?",
                    color = urgencyColor,
                    fontWeight = FontWeight.Bold,
                    fontSize = 18.sp
                )
            }

            Column(Modifier.weight(1f)) {
                Text(
                    summary.callerName,
                    color = TextPrimary,
                    fontWeight = FontWeight.SemiBold,
                    fontSize = 15.sp,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                Text(
                    dateStr,
                    color = TextMuted,
                    fontSize = 12.sp
                )
                if (summary.wasAutoAnswered) {
                    Text(
                        "🤖 Auto-answered by Jarvis",
                        color = CyanGlow.copy(alpha = 0.7f),
                        fontSize = 11.sp
                    )
                } else if (summary.wasDeclined) {
                    Text(
                        "📵 Declined",
                        color = RoseAccent.copy(alpha = 0.7f),
                        fontSize = 11.sp
                    )
                }
            }

            Column(horizontalAlignment = Alignment.End) {
                // Urgency badge
                Text(
                    urgencyLabel,
                    color = urgencyColor,
                    fontSize = 10.sp,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier
                        .clip(RoundedCornerShape(6.dp))
                        .background(urgencyColor.copy(alpha = 0.12f))
                        .padding(horizontal = 6.dp, vertical = 3.dp)
                )
                Spacer(Modifier.height(4.dp))
                // Language badge
                Text(
                    summary.detectedLanguage,
                    color = TextMuted,
                    fontSize = 10.sp,
                    modifier = Modifier
                        .clip(RoundedCornerShape(6.dp))
                        .background(Color(0xFF1A2030))
                        .padding(horizontal = 6.dp, vertical = 3.dp)
                )
            }
        }

        // Caller reason preview — always visible
        if (summary.callerReason.isNotBlank()) {
            Text(
                "\"${summary.callerReason.take(100)}${if (summary.callerReason.length > 100) "…" else ""}\"",
                color = TextSecondary,
                fontSize = 12.sp,
                modifier = Modifier.padding(horizontal = 16.dp).padding(bottom = 8.dp)
            )
        }

        // Action required chip
        if (summary.actionRequired.isNotBlank()) {
            Text(
                "Action: ${summary.actionRequired}",
                color = urgencyColor,
                fontSize = 12.sp,
                fontWeight = FontWeight.Medium,
                modifier = Modifier
                    .padding(horizontal = 16.dp)
                    .padding(bottom = 8.dp)
                    .clip(RoundedCornerShape(6.dp))
                    .background(urgencyColor.copy(alpha = 0.08f))
                    .padding(horizontal = 8.dp, vertical = 4.dp)
            )
        }

        // Expand/collapse row
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 4.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            TextButton(onClick = onToggleExpand) {
                Text(
                    if (isExpanded) "Show less ▲" else "Show full summary ▼",
                    color = CyanGlow.copy(alpha = 0.7f),
                    fontSize = 12.sp
                )
            }
            IconButton(onClick = onDelete, modifier = Modifier.size(32.dp)) {
                Icon(
                    Icons.Default.DeleteOutline,
                    "Delete",
                    tint = TextMuted,
                    modifier = Modifier.size(18.dp)
                )
            }
        }

        // Expanded details
        if (isExpanded) {
            HorizontalDivider(
                color = Color(0xFF1A2030),
                modifier = Modifier.padding(horizontal = 16.dp)
            )
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                InfoRow("Duration", formatDuration(summary.durationSeconds))
                InfoRow("Language", summary.detectedLanguage)
                InfoRow("Category", urgencyLabel)
                if (summary.callerNumber.isNotBlank()) {
                    InfoRow("Number", summary.callerNumber)
                }
                Spacer(Modifier.height(4.dp))
                Text(
                    "Full Summary",
                    color = TextSecondary,
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold
                )
                Text(
                    summary.summaryText,
                    color = TextPrimary,
                    fontSize = 13.sp,
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(8.dp))
                        .background(Color(0x0AFFFFFF))
                        .padding(12.dp)
                )
            }
        }
    }
}

@Composable
private fun InfoRow(label: String, value: String) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(label, color = TextMuted, fontSize = 12.sp)
        Text(value, color = TextSecondary, fontSize = 12.sp, fontWeight = FontWeight.Medium)
    }
}

@Composable
private fun EmptyCallSummaryPlaceholder(modifier: Modifier = Modifier) {
    Box(
        modifier = modifier.fillMaxSize(),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Text("📋", fontSize = 48.sp)
            Text(
                "No Call Summaries Yet",
                color = TextPrimary,
                fontWeight = FontWeight.SemiBold,
                fontSize = 18.sp
            )
            Text(
                "When Jarvis handles a call, a concise summary\nwill appear here.",
                color = TextMuted,
                fontSize = 13.sp,
                lineHeight = 20.sp
            )
        }
    }
}

private fun formatDuration(seconds: Int): String {
    val m = seconds / 60
    val s = seconds % 60
    return if (m > 0) "${m}m ${s}s" else "${s}s"
}
